{
 "bad": [
  "IPython.core.debugger.BdbQuit_excepthook",
  "IPython.core.debugger.BdbQuit_excepthook.excepthook_ori",
  "IPython.get_ipython",
  "IPython.terminal.embed.InteractiveShellEmbed",
  "IPython.terminal.ipapp.TerminalIPythonApp",
  "IPython.utils.io.stdout",
  "contextlib.contextmanager",
  "post_mortem",
  "set_trace"
 ],
 "deps": [
  [
   "ipdb-0.11-py_1",
   "ipdb-0.11-py_2"
  ],
  [
   "pdbpp-0.10.0-py_0",
   "pdbpp-0.9.1-py27_0",
   "pdbpp-0.9.1-py27_1",
   "pdbpp-0.9.1-py35_1",
   "pdbpp-0.9.11-py_0",
   "pdbpp-0.9.12-py_0",
   "pdbpp-0.9.13-py_0",
   "pdbpp-0.9.14-py_0",
   "pdbpp-0.9.15-py_0",
   "pdbpp-0.9.5-py_1",
   "pdbpp-0.9.6-py_0",
   "pdbpp-0.9.7-py_0",
   "pdbpp-0.9.8-py_0"
  ]
 ]
}