{
 "bad": [
  "_pytest._code.ExceptionInfo",
  "_pytest._code.code.ReprEntry",
  "_pytest._code.code.ReprEntryNative",
  "_pytest._code.code.ReprExceptionInfo",
  "_pytest._code.code.ReprFileLocation",
  "_pytest._code.code.ReprFuncArgs",
  "_pytest._code.code.ReprLocals",
  "_pytest._code.code.ReprTraceback",
  "assembled_report",
  "call",
  "collections.OrderedDict",
  "difflib.unified_diff",
  "itertools.cycle",
  "method",
  "multiprocessing.cpu_count",
  "notify",
  "os.sched_getaffinity",
  "pprint.pprint",
  "py.log.Producer",
  "six.moves.queue.Empty",
  "six.moves.queue.Queue",
  "val"
 ],
 "deps": [
  [],
  [
   "pytest-xdist-1.22.4-0",
   "pytest-xdist-1.22.5-0",
   "pytest-xdist-1.23.0-0",
   "pytest-xdist-1.23.0-py_0",
   "pytest-xdist-1.23.1-py_0",
   "pytest-xdist-1.23.2-py_0",
   "pytest-xdist-1.24.0-py_0"
  ]
 ]
}