{
 "bad": [
  "colcon_core.package_identification.logger.error",
  "getter",
  "os.chdir",
  "os.getcwd",
  "os.path.join",
  "sys",
  "sys.executable",
  "sys.platform"
 ],
 "deps": {
  "ast": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "colcon_core": [
   "colcon-core/conda-forge/linux-64/colcon-core-0.6.0-py37hc8dfbb8_0"
  ],
  "distutils": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "getter": [],
  "os": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "pathlib": [
   "pathlib/conda-forge/noarch/pathlib-1.0.1-py_1",
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "runpy": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "setuptools": [
   "setuptools/conda-forge/linux-64/setuptools-41.2.0-py27_0"
  ],
  "subprocess": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "sys": [],
  "threading": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ]
 }
}