{
 "bad": [
  "Exception",
  "RuntimeError",
  "ValueError",
  "len",
  "open",
  "print",
  "sos.utils.env.log_to_file",
  "sos.utils.env.logger.debug",
  "sos.utils.env.logger.error",
  "sos.utils.env.logger.info",
  "sos.utils.env.logger.trace",
  "sos.utils.env.logger.warning",
  "str",
  "super"
 ],
 "deps": [
  [
   "sos-0.20.10-py_0",
   "sos-0.20.11-py_0",
   "sos-0.20.12-py_0",
   "sos-0.20.13-py_0",
   "sos-0.20.9-py_0",
   "sos-0.21.1-py_0",
   "sos-0.21.11-py_0",
   "sos-0.21.12-py_0",
   "sos-0.21.13-py_0",
   "sos-0.21.15-py_0",
   "sos-0.21.16-pyhd8ed1ab_0",
   "sos-0.21.2-py_0",
   "sos-0.21.3-py_0",
   "sos-0.21.5-py_0",
   "sos-0.21.6-py_0",
   "sos-0.21.7-py_0",
   "sos-0.21.8-py_0",
   "sos-0.22.2-pyhd8ed1ab_0",
   "sos-0.22.4-pyhd8ed1ab_0"
  ],
  [
   "sos-pbs-0.20.3-py_0",
   "sos-pbs-0.20.5-py_0",
   "sos-pbs-0.20.6-py_0",
   "sos-pbs-0.20.7-py_0",
   "sos-pbs-0.20.8-py_0"
  ]
 ]
}