{
 "bad": [
  "google.auth.exceptions",
  "google.auth.exceptions.TransportError",
  "google.auth.transport",
  "google.auth.transport.Request",
  "google.auth.transport.Response"
 ],
 "deps": {
  "__future__": [
   "python/conda-forge/linux-64/python-2.7.14-3",
   "python/conda-forge/linux-64/python-2.7.15-h938d71a_1004",
   "python/conda-forge/linux-64/python-3.5.4-0",
   "python/conda-forge/linux-64/python-3.6.10-he5300dc_1011_cpython",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_6_cpython",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_8_cpython",
   "python/conda-forge/linux-64/python-3.9.0-h2a148a8_4_cpython"
  ],
  "httplib2": [
   "httplib2/conda-forge/noarch/httplib2-0.19.0-pyhd8ed1ab_0"
  ],
  "logging": [
   "python/conda-forge/linux-64/python-2.7.15-h938d71a_1004",
   "python/conda-forge/linux-64/python-3.5.4-0",
   "python/conda-forge/linux-64/python-3.6.10-he5300dc_1011_cpython",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_6_cpython",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_8_cpython",
   "python/conda-forge/linux-64/python-3.9.0-h2a148a8_4_cpython"
  ]
 }
}