{
 "bad": [
  "_fix_exception_context",
  "callback",
  "cb",
  "contextlib2.__init__.AbstractAsyncContextManager",
  "contextlib2.__init__.AbstractContextManager",
  "contextlib2.__init__.AsyncContextDecorator",
  "contextlib2.__init__.ContextDecorator",
  "contextlib2.__init__.ExitStack",
  "contextlib2.__init__._AsyncGeneratorContextManager",
  "contextlib2.__init__._BaseExitStack",
  "contextlib2.__init__._GeneratorContextManager",
  "contextlib2.__init__._GeneratorContextManagerBase",
  "contextlib2.__init__._RedirectStream",
  "contextlib2.__init__.__all__",
  "func",
  "sys",
  "sys.exc_info",
  "typ",
  "types.GenericAlias",
  "warnings",
  "warnings.warn"
 ],
 "deps": {
  "_collections_abc": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "_fix_exception_context": [],
  "abc": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "callback": [],
  "cb": [],
  "collections": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "contextlib2": [],
  "func": [],
  "functools": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "sys": [],
  "typ": [],
  "types": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "warnings": []
 }
}