{
 "bad": [
  "atexit",
  "atexit.register",
  "errno",
  "errno.EEXIST",
  "importlib_resources.trees.as_file",
  "os.path.basename",
  "os.path.dirname",
  "os.path.exists",
  "os.path.isdir",
  "os.path.isfile",
  "os.path.join",
  "os.path.realpath",
  "os.rename",
  "remote_files.is_known_remote",
  "remote_files.remote_file",
  "sys",
  "sys.version_info",
  "urllib.urlretrieve"
 ],
 "deps": {
  "__future__": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "argparse": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "atexit": [],
  "contextlib": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "contextlib2": [
   "contextlib2/conda-forge/noarch/contextlib2-21.6.0-pyhd8ed1ab_0"
  ],
  "errno": [],
  "importlib_resources": [
   "importlib_resources/conda-forge/noarch/importlib_resources-5.1.4-pyhd8ed1ab_0"
  ],
  "logging": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "os": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "remote_files": [],
  "sys": [],
  "tarfile": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "urllib": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "yaml": [
   "google-cloud-bigquery-storage-core/conda-forge/noarch/google-cloud-bigquery-storage-core-2.0.0-pyh9f0ad1d_1",
   "pyyaml/conda-forge/linux-64/pyyaml-5.4.1-py36h70b1f00_0"
  ]
 }
}