{
 "bad": [
  "_kwargs_get",
  "boto.log.debug",
  "boto.log.error",
  "exception_class",
  "urllib.urlencode"
 ],
 "deps": {
  "_kwargs_get": [],
  "boto": [
   "boto/conda-forge/noarch/boto-2.49.0-py_0"
  ],
  "exception_class": [],
  "json": [
   "python/conda-forge/linux-64/python-3.5.3-1",
   "python/conda-forge/linux-64/python-3.6.6-h5001a0f_0",
   "python/conda-forge/linux-64/python-3.7.0-h5001a0f_4",
   "python/conda-forge/linux-64/python-3.7.8-hffdb5ce_3_cpython",
   "python/conda-forge/linux-64/python-3.8.0-h357f687_1",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_4_cpython",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_5_cpython"
  ],
  "os": [
   "python/conda-forge/linux-64/python-3.5.3-1",
   "python/conda-forge/linux-64/python-3.6.6-h5001a0f_0",
   "python/conda-forge/linux-64/python-3.7.0-h5001a0f_4",
   "python/conda-forge/linux-64/python-3.7.8-hffdb5ce_3_cpython",
   "python/conda-forge/linux-64/python-3.8.0-h357f687_1",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_4_cpython",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_5_cpython"
  ],
  "urllib": [
   "python/conda-forge/linux-64/python-3.5.3-1",
   "python/conda-forge/linux-64/python-3.6.6-h5001a0f_0",
   "python/conda-forge/linux-64/python-3.7.0-h5001a0f_4",
   "python/conda-forge/linux-64/python-3.7.8-hffdb5ce_3_cpython",
   "python/conda-forge/linux-64/python-3.8.0-h357f687_1",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_4_cpython",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_5_cpython"
  ]
 }
}