{
 "bad": [
  "IndexError",
  "bool",
  "fault_localization.tracing.TRACER.flush_buffer",
  "fault_localization.tracing.TRACER.trace",
  "float",
  "getattr",
  "int",
  "max",
  "min",
  "object",
  "open",
  "operator.attrgetter",
  "range",
  "round",
  "set",
  "sorted",
  "sum",
  "try_get_line",
  "tuple",
  "zip"
 ],
 "deps": [
  [
   "fault-localization-0.1.6-py_0"
  ]
 ]
}