{
 "bad": [
  "fault_localization.tracing.TRACER.flush_buffer",
  "fault_localization.tracing.TRACER.trace",
  "operator.attrgetter",
  "try_get_line"
 ],
 "deps": [
  [
   "fault-localization-0.1.6-py_0"
  ]
 ]
}