{
 "bad": [
  "collections.defaultdict",
  "collections.namedtuple",
  "fault_localization.tracing.TRACER.flush_buffer",
  "fault_localization.tracing.TRACER.trace",
  "operator.attrgetter",
  "os.getcwd",
  "os.path.abspath",
  "os.path.relpath",
  "pytest.hookimpl",
  "sys.settrace"
 ],
 "deps": [
  [
   "fault-localization-0.1.3-py_0",
   "fault-localization-0.1.6-py_0"
  ]
 ]
}