{
 "bad": [
  "Cache",
  "Cache.from_json",
  "Exception.__init__",
  "Item",
  "ItemGroup",
  "ItemList",
  "requests_oauthlib.OAuth2Session",
  "urllib.urlencode"
 ],
 "deps": [
  [
   "oauthlib-2.0.1-py36_0",
   "oauthlib-2.0.4-py_0",
   "oauthlib-2.0.6-py_0",
   "oauthlib-2.0.7-py_0",
   "oauthlib-2.1.0-py_0",
   "oauthlib-3.0.1-py_0"
  ],
  [
   "pyalveo-1.0.5-py_0"
  ]
 ]
}